<?php

namespace App\Console\Commands;

use App\Integrations\Contracts\Step;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class MakeIntegrationCommand extends Command
{
    protected $signature = 'integrations:make';

    protected $description = 'Scaffold a disk integration with a group and flow (interactive prompts).';

    public function handle(): int
    {
        $this->info('New integration (under integrations/).');
        $this->newLine();

        $basePath = (string) config('flows.integrations_path', base_path('integrations'));
        $basePath = rtrim($basePath, DIRECTORY_SEPARATOR);

        $slug = $this->askIntegrationSlug();
        $integrationDir = $basePath.DIRECTORY_SEPARATOR.$slug;

        if (File::isDirectory($integrationDir)) {
            if (! $this->confirm("Directory [{$integrationDir}] already exists. Overwrite files generated by this command?", false)) {
                $this->warn('Aborted.');

                return self::FAILURE;
            }
        }

        $key = $this->askIntegrationKey($slug);
        $name = $this->askIntegrationName($slug);
        $groupSlug = $this->askSegmentSlug('Group slug', 'default');
        $flowSlug = $this->askSegmentSlug('Flow slug', 'main');

        $generateStep = $this->confirm('Generate an entry Step class inside the integration folder?', true);

        $entryFqcn = null;

        if ($generateStep) {
            $studlyIntegration = Str::studly(str_replace('-', '_', $slug));
            $studlyGroup = Str::studly(str_replace('-', '_', $groupSlug));
            $studlyFlow = Str::studly(str_replace('-', '_', $flowSlug));
            $defaultStep = $studlyIntegration.'EntryStep';
            $stepClass = $this->ask('Step class name', $defaultStep);
            $stepClass = is_string($stepClass) ? trim($stepClass) : '';
            if ($stepClass === '' || ! preg_match('/^[A-Z][a-zA-Z0-9]*$/', $stepClass)) {
                $this->error('Invalid class name (use PascalCase).');

                return self::FAILURE;
            }

            $flowDefinitionName = $name.' — '.$flowSlug;
            $namespace = 'Integrations\\'.$studlyIntegration.'\\Groups\\'.$studlyGroup.'\\Flows\\'.$studlyFlow;
            $entryFqcn = $namespace.'\\'.$stepClass;
            $flowDir = $integrationDir.DIRECTORY_SEPARATOR.'groups'.DIRECTORY_SEPARATOR.$groupSlug.DIRECTORY_SEPARATOR.'flows'.DIRECTORY_SEPARATOR.$flowSlug;
            File::ensureDirectoryExists($flowDir);
            $stepPath = $flowDir.DIRECTORY_SEPARATOR.$stepClass.'.php';

            if (File::exists($stepPath) && ! $this->confirm("File [{$stepPath}] already exists. Overwrite?", false)) {
                $this->warn('Aborted.');

                return self::FAILURE;
            }

            File::put($stepPath, $this->stepClassContents($namespace, $stepClass, $flowDefinitionName));
            $stepRelativePath = Str::after($stepPath, base_path().DIRECTORY_SEPARATOR);
            $this->info("Step created: {$stepRelativePath}");
        } else {
            $entryFqcn = $this->askExistingStepFqcn();
            if ($entryFqcn === null) {
                return self::FAILURE;
            }
        }

        if (! $generateStep) {
            File::ensureDirectoryExists($integrationDir.DIRECTORY_SEPARATOR.'groups'.DIRECTORY_SEPARATOR.$groupSlug.DIRECTORY_SEPARATOR.'flows'.DIRECTORY_SEPARATOR.$flowSlug);
        }

        File::put($integrationDir.DIRECTORY_SEPARATOR.'config.php', $this->integrationConfigContents($key, $name));
        File::put($integrationDir.DIRECTORY_SEPARATOR.'groups'.DIRECTORY_SEPARATOR.$groupSlug.DIRECTORY_SEPARATOR.'config.php', $this->groupConfigContents($groupSlug));
        File::put(
            $integrationDir.DIRECTORY_SEPARATOR.'groups'.DIRECTORY_SEPARATOR.$groupSlug.DIRECTORY_SEPARATOR.'flows'.DIRECTORY_SEPARATOR.$flowSlug.DIRECTORY_SEPARATOR.'flow.php',
            $this->flowConfigContents($entryFqcn),
        );

        $flowRef = "{$slug}/{$groupSlug}/{$flowSlug}";
        $this->newLine();
        $this->info("Integration ready. flow_ref: [{$flowRef}]");
        $this->line('  Validate: php artisan flows:validate');
        $this->line("  Run: php artisan flows:run {$flowRef}");

        $this->newLine();
        $code = $this->call('flows:validate');
        if ($code !== self::SUCCESS) {
            $this->warn('flows:validate finished with errors; check the output above.');

            return self::FAILURE;
        }

        return self::SUCCESS;
    }

    private function askIntegrationSlug(): string
    {
        while (true) {
            $slug = $this->ask('Integration folder slug (kebab-case, e.g. shopify)');
            $slug = is_string($slug) ? trim($slug) : '';
            if ($slug === '') {
                $this->error('Slug is required.');

                continue;
            }
            if (! preg_match('/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/', $slug)) {
                $this->error('Use lowercase letters, numbers, and hyphens only; must start with a letter.');

                continue;
            }

            return $slug;
        }
    }

    private function askIntegrationKey(string $slug): string
    {
        $key = $this->ask('Integration key', $slug);
        $key = is_string($key) ? trim($key) : '';

        return $key !== '' ? $key : $slug;
    }

    private function askIntegrationName(string $slug): string
    {
        $default = Str::title(str_replace('-', ' ', $slug));
        $name = $this->ask('Integration display name', $default);
        $name = is_string($name) ? trim($name) : '';

        return $name !== '' ? $name : $default;
    }

    private function askSegmentSlug(string $label, string $default): string
    {
        while (true) {
            $value = $this->ask($label." (kebab-case, default: {$default})", $default);
            $value = is_string($value) ? trim($value) : '';
            if ($value === '') {
                $value = $default;
            }
            if (! preg_match('/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/', $value)) {
                $this->error('Invalid slug.');

                continue;
            }

            return $value;
        }
    }

    private function askExistingStepFqcn(): ?string
    {
        while (true) {
            $fqcn = $this->ask('Fully qualified Step class name (must exist and implement Step)');
            $fqcn = is_string($fqcn) ? trim($fqcn) : '';
            if ($fqcn === '') {
                $this->error('Class name is required.');

                continue;
            }
            if (! class_exists($fqcn)) {
                $this->error('Class does not exist or is not autoloadable.');

                continue;
            }
            if (! is_subclass_of($fqcn, Step::class)) {
                $this->error('Class must implement '.Step::class.'.');

                continue;
            }

            return $fqcn;
        }
    }

    private function integrationConfigContents(string $key, string $name): string
    {
        $keyExport = var_export($key, true);
        $nameExport = var_export($name, true);

        return <<<PHP
<?php

return [
    'key' => {$keyExport},
    'name' => {$nameExport},
    'image_url' => null,
    'extra_config' => [],
    'failure_notifications' => [
        'mail' => [],
        'slack_webhook_url' => null,
        'teams_workflow_webhook_url' => null,
    ],
];

PHP;
    }

    private function groupConfigContents(string $groupSlug): string
    {
        $groupExport = var_export($groupSlug, true);

        return <<<PHP
<?php

return [
    'extra_config' => [
        'group' => {$groupExport},
    ],
];

PHP;
    }

    private function flowConfigContents(string $entryFqcn): string
    {
        $entryShort = Str::afterLast($entryFqcn, '\\');
        $useStatement = "use {$entryFqcn};";

        return <<<PHP
<?php

{$useStatement}

return [
    'entry' => [
        {$entryShort}::class,
    ],
];

PHP;
    }

    private function stepClassContents(string $namespace, string $class, string $flowDefinitionName): string
    {
        $nameExport = var_export($flowDefinitionName, true);
        $logMessage = var_export($flowDefinitionName.' — entry step', true);

        return <<<PHP
<?php

namespace {$namespace};

use App\Integrations\Contracts\DefinesFlowMetadata;
use App\Integrations\Contracts\Step;
use App\Integrations\DiskFlowContext;
use App\Integrations\StepResult;

final class {$class} implements DefinesFlowMetadata, Step
{
    public static function flowDefinitionName(): string
    {
        return {$nameExport};
    }

    public static function flowDefinitionIsActive(): bool
    {
        return true;
    }

    public static function flowDefinitionExtraConfig(): array
    {
        return [];
    }

    public function run(DiskFlowContext \$context): StepResult
    {
        \$context->logs->info({$logMessage});

        return new StepResult(
            ['status' => 'ok'],
            null,
        );
    }
}

PHP;
    }
}
